name: life_legacy_manager
description: Life & Legacy Manager app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Icons
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.4.0
  riverpod: ^2.4.0

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1+1
  path: ^1.8.3

  # Security / login / crypto
  crypto: ^3.0.3
  uuid: ^3.0.7
  local_auth: ^2.1.7

  # Export / Sharing
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  
  # File picker voor import
  file_picker: ^6.1.1
  
  # PDF generation
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true